### ISSUE TITLE
Is there any way to run without chrome extension?

### ISSUE THREAD

**Issue by yisar** [hazae41/ethbrno-wallet#3]
such as `http://localhost:3000`

**Comment by hazae41** [comment]
No, but you can have an example of Tor on a website on https://github.com/hazae41/echalote in `test`

**Comment by hazae41** [comment]
You can use the new version https://github.com/brumewallet/wallet that runs on a website

**Comment by yisar** [comment]
> You can use the new version https://github.com/brumewallet/wallet that runs on a website

That is great, thank you, If I have new problems, I will open the issues on the new version.
